// Generated by CoffeeScript 1.5.0
(function() {
  var makeModal, modalTmpl, modalTmplPre;

  modalTmplPre = "<div id=\"requestModal\" class=\"modal hide fade\" tabindex=\"-1\" role=\"dialog\" aria-labeledby=\"requestModal\" aria-hidden=\"true\">\n    <div class=\"modal-header\">\n        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\"><i class=\"icon-remove\"></i></button>\n        <h3 class=\"text-{{textColor}}\"><i class=\"icon-{{icon}}\"></i> {{modalTitle}}</h3>\n    </div>\n    <div class=\"modal-body\">\n    <p class=\"text-{{textColor}}\">{{{text}}}</p>\n    </div>\n    <div class=\"modal-footer\">\n        <div class=\"btn-group\">\n            <a class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\">Close</a>\n            <button class=\"btn btn-{{btnColor}}\" type=\"submit\" id=\"modalButton\" data-loading-text=\"{{btnLoadingText}}\"><i class=\"icon-{{icon}}\"></i> {{btnText}}</button>\n        </div>\n    </div>\n</div>";

  modalTmpl = Handlebars.compile(modalTmplPre);

  makeModal = function(data) {
    $("#modal").html(modalTmpl(data));
    $("#requestModal").modal();
    $("#requestModal").modal('show');
    $("#requestModal").on('shown', function() {
      $("#modalButton").button();
      return $("#modalButton").click(function() {
        return $(this).button('loading');
      });
    });
    /*
    Clear the HTML we threw into the page after the modal is gone,
    not sure if this is needed since the page probably will redirect
    */

    return $('#requestModal').on('hidden', function() {
      return $("modal").html("");
    });
  };

  this.modalDelete = function(title, text) {
    var modalData;
    modalData = {
      "btnText": "Delete",
      "ModalTitle": title,
      "btnColor": "danger",
      "textColor": "error",
      "text": text,
      "icon": "trash",
      "btnLoadingText": "Deleting..."
    };
    return makeModal(modalData);
  };

  this.modalEdit = function(title, text) {
    var modalData;
    modalData = {
      "btnText": "Edit",
      "modalTitle": title,
      "btnColor": "primary",
      "textColor": "",
      "text": text,
      "icon": "edit",
      "btnLoadingText": "Updating..."
    };
    return makeModal(modalData);
  };

  this.modalGrant = function(title, text) {
    var modalData;
    modalData = {
      "btnText": "Grant",
      "modalTitle": title,
      "btnColor": "success",
      "textColor": "success",
      "text": text,
      "icon": "ok",
      "btnLoadingText": "Granting..."
    };
    return makeModal(modalData);
  };

  this.modalNew = function(title, text) {
    var modalData;
    modalData = {
      "btnText": "Create",
      "modalTitle": title,
      "btnColor": "info",
      "textColor": "info",
      "text": text,
      "icon": "ok",
      "btnLoadingText": "Creating..."
    };
    return makeModal(modalData);
  };

  this.editForm = function(action, value) {
    var jsonVal;
    jsonVal = $.toJSON(value);
    $("#editFormInput").val(jsonVal);
    return $("#editForm").attr('action', action);
  };

}).call(this);
