// Generated by CoffeeScript 1.5.0
(function() {

  $(function() {
    return $("#deleteButton").click(function() {
      var box, mod, text, values, _i, _len, _ref;
      values = [];
      _ref = $(".bulkCheckbox:checked");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        box = _ref[_i];
        values.push($(box).val());
      }
      text = "You're about to delete all of these templates! Are you sure you want to take the chance of setting fire to all of fla.gr by deleting possibly used templates?";
      mod = new deleteModal("Delete all of these?", text);
      mod.make();
      editForm('/admin/templates/delete', values);
      return $("#modalButton").click(function() {
        return $("#editForm").submit();
      });
    });
  });

}).call(this);
