// Generated by CoffeeScript 1.5.0
(function() {

  $(function() {
    return $("#bulkCheckButton").click(function() {
      if ($("#bulkCheckButton").hasClass('active')) {
        return $(".bulkCheckbox").prop('checked', false);
      } else {
        return $(".bulkCheckbox").prop('checked', true);
      }
    });
  });

}).call(this);
