// Generated by CoffeeScript 1.5.0
(function() {

  $(function() {
    var deleteModalTmpl, deleteModalTmplPre, grantModalTmpl, grantModalTmplPre;
    deleteModalTmplPre = "<div id=\"requestDeleteModal\" class=\"modal hide fade\" tabindex=\"-1\" role=\"dialog\" aria-labeledby=\"tmplDeleteModal\" aria-hidden=\"true\">\n    <div class=\"modal-header\">\n        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\"><i class=\"icon-remove\"></i></button>\n        <h3 class=\"text-error\"><i class=\"icon-trash\"></i> Delete request by `{{email}}`?</h3>\n    </div>\n    <div class=\"modal-body\">\n        <p class=\"text-error\">You're about to delete this invite request?</p>\n        <p class=\"text-error\">Are you sure you want to do this? Do you really want to crush their soul? Are you really that horrible? Maybe I should take away your lemons...</p>\n    </div>\n    <div class=\"modal-footer\">\n        <form action=\"/admin/requests/{{id}}/delete\" method=\"POST\">\n            <div class=\"btn-group\">\n                <a class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\">Close</a>\n                <button class=\"btn btn-danger\" type=\"submit\" id=\"deleteButton\" data-loading-text=\"Deleting...\"><i class=\"icon-trash\"></i> Delete</button>\n            </div>\n        </form>\n    </div>\n</div>";
    grantModalTmplPre = "<div id=\"requestGrantModal\" class=\"modal hide fade\" tabindex=\"-1\" role=\"dialog\" aria-labeledby=\"tmplDeleteModal\" aria-hidden=\"true\">\n    <div class=\"modal-header\">\n        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\"><i class=\"icon-remove\"></i></button>\n        <h3 class=\"text-success\"><i class=\"icon-trash\"></i> Grant request by `{{email}}`?</h3>\n    </div>\n    <div class=\"modal-body\">\n        <p class=\"text-success\">Yay! You're granting someones invite request and letting them have a stab at fla.gr and using it! Good for you, you deserve more lemons.</p>\n    </div>\n    <div class=\"modal-footer\">\n        <form action=\"/admin/requests/{{id}}/edit\" method=\"POST\">\n            <div class=\"btn-group\">\n                <a class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\">Close</a>\n                <button class=\"btn btn-success\" type=\"submit\" id=\"grantButton\" data-loading-text=\"Grant...\"><i class=\"icon-ok\"></i> Grant</button>\n            </div>\n            <input type=\"hidden\" value=\"grant\" name=\"grant\">\n        </form>\n    </div>\n</div>";
    deleteModalTmpl = Handlebars.compile(deleteModalTmplPre);
    grantModalTmpl = Handlebars.compile(grantModalTmplPre);
    /*
    Theres probably a much much better and DRY way to do this, but heres a quick
    hack instead...
    */

    /*
    When the user presses the delete button, generate the modal, throw it into
    the page and hope for the best.
    */

    $(".requestDeleteButton").click(function() {
      var email, id;
      email = $(this).data("email");
      id = $(this).data("id");
      $("#modal").html(deleteModalTmpl({
        "email": email,
        "id": id
      }));
      $("#requestDeleteModal").modal();
      $("#requestDeleteModal").modal('show');
      $("#requestDeleteModal").on('shown', function() {
        $("#deleteButton").button();
        return $("#deleteButton").click(function() {
          return $(this).button('loading');
        });
      });
      /*
      Clear the HTML we threw into the page after the modal is gone,
      not sure if this is needed since the page probably will redirect
      to /admin/templates if I'm correct...
      */

      return $('#requestDeleteModal').on('hidden', function() {
        return $("modal").html("");
      });
    });
    /*
    When the user presses the grant button, generate the modal, throw it into
    the page and hope for the best. Just like deletes
    */

    return $(".requestGrantButton").click(function() {
      var email, id;
      email = $(this).data("email");
      id = $(this).data("id");
      $("#modal").html(grantModalTmpl({
        "email": email,
        "id": id
      }));
      $("#requestGrantModal").modal();
      $("#requestGrantModal").modal('show');
      $("#requestGrantModal").on('shown', function() {
        $("#grantButton").button();
        return $("#grantButton").click(function() {
          return $(this).button('loading');
        });
      });
      /*
      Clear the HTML we threw into the page after the modal is gone,
      not sure if this is needed since the page probably will redirect
      to /admin/templates if I'm correct...
      */

      return $('#requestGrantModal').on('hidden', function() {
        return $("modal").html("");
      });
    });
  });

}).call(this);
