// Generated by CoffeeScript 1.5.0
(function() {

  $(function() {
    return $(".modal-options-btn").click(function() {
      var bucket, elem;
      elem = $(this);
      bucket = elem.data("bucket");
      return $.post("/admin/dev/buckets", {
        json: "{\"bucket\": \"" + bucket + "\"}"
      }, function(data) {
        if (data["status"]) {
          if (elem.hasClass("btn-inverse")) {
            elem.removeClass("btn-inverse");
            elem.addClass("btn-success");
            return elem.html("<i class=\"icon-bolt\"></i> Enabled");
          } else if (elem.hasClass("btn-success")) {
            elem.addClass("btn-inverse");
            elem.removeClass("btn-success");
            return elem.html("<i class=\"icon-off\"></i> Disabled");
          }
        }
      });
    });
  });

}).call(this);
