// Generated by CoffeeScript 1.5.0
(function() {

  this.editForm = function(action, value) {
    var jsonVal;
    jsonVal = $.toJSON(value);
    $("#editFormInput").val(jsonVal);
    return $("#editForm").attr('action', action);
  };

}).call(this);
