// Generated by CoffeeScript 1.5.0
(function() {

  $(function() {
    /*
    Setup the various focus events for the forms in the dropdown menus...
    */

    var _this = this;
    $("#dropdownSearchToggle").click(function() {
      return setTimeout(function() {
        return $("#dropdownSearchInput").focus();
      }, 10);
    });
    $("#dropdownLoginToggle").click(function() {
      return setTimeout(function() {
        return $("#dropdownLoginEmail").focus();
      }, 10);
    });
    return $("#dropdownLoginEmail").keypress(function(event) {
      if (event.which === 13) {
        event.preventDefault();
        return setTimeout(function() {
          return $("#dropdownLoginPassword").focus();
        }, 10);
      }
    });
  });

}).call(this);
