// Generated by CoffeeScript 1.5.0
(function() {

  $(function() {
    /*
    Activate the tabs
    */
    $('#sidebarTabs a').click(function(e) {
      e.preventDefault();
      return $(this).tab('show');
    });
    return $("#sidebarTabs a.btn").click(function(e) {
      return e.preventDefault();
    });
  });

}).call(this);
